language: python
python:
  - "3.6"
cache: pip
install:
  - pip3 install -r requirements.txt
script:
  - python3 -m pytest -v tests/test_main.py
    # uncomment the following line for extra credit
  - python3 -m pytest -v tests/test_ec.py
